let a = 'hello';
console.log(a);
alert(a);
document.write(a);
let aa3 = false;
console.log(aa3);
let a2 = true;
console.log(a2);
let b = 'owu';
console.log(b);
alert(b);
document.write(b);
let b1 = false;
console.log(b1);
let b2 = true;
console.log(b1);
let c = 'com';
console.log(c);
alert(c);
document.write(c);
let c1 = false;
console.log(c1);
let c2 = true;
console.log(c2);
let d = 'ua';
console.log(d);
alert(d);
document.write(d);
let d1 = false;
console.log(d1);
let d2 = true;
console.log(d2);
let a1 = 1 ;
console.log(a1);
alert(a1);
document.write(a1);
let a11 = false;
console.log(a11);
let a12 = true;
console.log(a12);
let a10 = 10 ;
console.log(a10);
alert(a10);
document.write(a10);
let aa10 = false;
console.log(aa10);
let aaa10 = true;
console.log(aaa10);
let number = -999 ;
console.log(number);
alert(number);
document.write(number);
let number1 = false;
console.log(number1);
let number22 = true;
console.log(number22);
let a123 = 123 ;
console.log(a123);
alert(a123);
document.write(a123);
let aa123 = false;
console.log(aa123);
let aaa123 = true;
console.log(aaa123);
let number2 = 3.14 ;
console.log(number2);
alert(number2);
document.write(number2)
let number23 = false;
console.log(number23);
let number232 = true;
console.log(number232);
let number3 = 2.7 ;
console.log(number3);
alert(number3);
document.write(number3)
let number33 = false;
console.log(number33);
let number34 = true;
console.log(number34);
let number4 = 16 ;
console.log(number4);
alert(number4);
document.write(number4)
let istrue=true;
alert(istrue);
document.write(istrue);
let isfolse=false;
alert(isfolse);
document.write(isfolse);
let firstName = 'Mariana';
console.log(firstName);
let lastName = 'Zalyciailo';
console.log(lastName);
let middleName = 'Bohdanivna';
console.log(middleName);
let person = `${lastName} ${firstName} ${middleName}`;
console.log(person);




